### ISSUE TITLE
More details on how to authenticate

### ISSUE THREAD

**Issue by benknight** [cloudapp/api#12]
Could you guys add some more specific information about how authentication is supposed to work?  Currently just have a link to the Wikipedia article "Digest access authentication".  That doesn't really tell me much.  How exactly do I use it with Cloud app?  Thanks.

**Comment by pashashocky** [comment]
curl --digest -u "arthur@dent.com:towel" \
     -H "Accept: application/json" \
     "https://my.cl.ly/v3/items"

http://developer.getcloudapp.com/#items
